"""Create class category and query it

Revision ID: 2913e1db42ac
Revises: a4f757a5aa3d
Create Date: 2020-07-17 14:32:54.255093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2913e1db42ac'
down_revision = 'a4f757a5aa3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'category')
    op.drop_table('categories')
    # ### end Alembic commands ###
