"""Authonticate Migration

Revision ID: 4287518c47dd
Revises: e812c7739bd4
Create Date: 2020-07-14 14:43:32.858127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4287518c47dd'
down_revision = 'e812c7739bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
