"""new tables created

Revision ID: 7c82a3f0b0d6
Revises: f82b5cd79640
Create Date: 2020-07-19 08:24:17.684791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c82a3f0b0d6'
down_revision = 'f82b5cd79640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('votes')
    op.add_column('comments', sa.Column('comment', sa.String(length=1000), nullable=True))
    op.add_column('comments', sa.Column('pitch', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitches_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch'], ['id'])
    op.drop_column('comments', 'time_posted')
    op.drop_column('comments', 'opinion')
    op.drop_column('comments', 'pitches_id')
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.String(length=1000), nullable=True))
    op.add_column('pitches', sa.Column('pitch_title', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'category_id')
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'date_joined')
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'pitch_title')
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'dislikes')
    op.drop_column('pitches', 'category')
    op.add_column('comments', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('opinion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('time_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitches_id_fkey', 'comments', 'pitches', ['pitches_id'], ['id'])
    op.drop_column('comments', 'pitch')
    op.drop_column('comments', 'comment')
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitches_id'], ['pitches.id'], name='votes_pitches_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='votes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
