"""add profile picture and bio increase number of characters

Revision ID: fcffb8736140
Revises: 4287518c47dd
Create Date: 2020-07-15 14:50:07.622544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcffb8736140'
down_revision = '4287518c47dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=False))
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
